import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { auth } from "@/auth";
import { Toaster } from "sonner";
import { User } from "next-auth";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface ExtendedUser extends User {
  username: string;
  location: string;
  website: string;
  about: string;
  github: string;
  twitter: string;
  instagram: string;
  medium: string;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <div className={cn(
      "min-h-screen bg-background flex flex-col justify-between font-sans antialiased",
      fontSans.variable
    )}>
      <Navbar data={session?.user as ExtendedUser} />
      {children}
      <Footer />
    </div>
  );
}
